services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app-chat
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql
    restart: always

  mysql_test:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app_chat_test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
